Added PUT Load tests
burntcarrot/yakv pull request #9
Opened 2021-10-03 19:47 UTC by SkandaSrinivasan

Hi I am done with the loadtests for PUT. Errors start at a rate of 8300 .

2021-10-04 03:48 UTC, burntcarrot requested changes

2021-10-04 03:48 UTC, burntcarrot commented on README.md
> +![PUT-Benchmark](benchmarks/put-loadtest-100s.png)
Could you please remove the old tests (line 166-181) and the old device specifications (line 154-162)?

2021-10-05 16:20 UTC, SkandaSrinivasan commented on README.md
> +![PUT-Benchmark](benchmarks/put-loadtest-100s.png)
Hi @burntcarrot , I have removed the old tests and related info. Let me know if anything else is needed.

2021-10-06 03:25 UTC, burntcarrot commented on README.md
> +![PUT-Benchmark](benchmarks/put-loadtest-100s.png)
Thanks for the changes!

2021-10-06 03:26 UTC, merged

2021-10-06 03:26 UTC, burntcarrot commented
@SkandaSrinivasan Thank you for your contribution!